name: auth_email
description: This is an easy way to authenticate user email with OTP using PHP as a backend in your own server.
version: 0.4.0
homepage: https://github.com/lamnhan066/auth_email

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.1.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
